device_index: 0
log_level: 0
top_n: 3
cnn_type: "mobilenet"
graph_file_path: "/opt/movidius/ncappzoo/tensorflow/mobilenets/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/imagenet1001.txt"
network_dimension: 224
channel1_mean: 127.5
channel2_mean: 127.5
channel3_mean: 127.5
scale: 0.007843
