device_index: 0
log_level: 0
top_n: 1
cnn_type: "tinyyolo_v1"
graph_file_path: "/opt/movidius/ncappzoo/caffe/TinyYolo/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/voc20.txt"
network_dimension: 448
channel1_mean: 0
channel2_mean: 0
channel3_mean: 0
scale: 0.00392156
